# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Example
  pod 'AssetLib', :path => '../'

  target 'iOS ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'macOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS Example
  pod 'AssetLib', :path => '../'

  target 'macOS ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tvOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tvOS Example
  pod 'AssetLib', :path => '../'

  target 'tvOS ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'watchOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOS Example
  pod 'AssetLib', :path => '../'

end

target 'watchOS Example Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOS Example Extension
  pod 'AssetLib', :path => '../'

end
