#if !canImport(ObjectiveC)
  import XCTest

  extension AssetSpecificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssetSpecificationTests = [
      ("testDecodingError", testDecodingError),
      ("testInvalidScale", testInvalidScale),
      ("testInvalidSize", testInvalidSize),
      ("testMetadata", testMetadata),
      ("testSpecifications", testSpecifications),
      ("testSuccessful", testSuccessful)
    ]
  }

  extension AssetTemplateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssetTemplateTests = [
      ("testTemplateBuilding", testTemplateBuilding)
    ]
  }

  extension ISDeviceIdiomProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ISDeviceIdiomProviderTests = [
      ("testInvalidDictionary", testInvalidDictionary),
      ("testValidDictionary", testValidDictionary)
    ]
  }

  extension IdiomScaleProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IdiomScaleProviderTests = [
      ("testDictionary", testDictionary)
    ]
  }

  extension ProductTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductTests = [
      ("testProduct", testProduct)
    ]
  }

  extension ValueAppearanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValueAppearanceTests = [
      ("testValues", testValues)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(AssetSpecificationTests.__allTests__AssetSpecificationTests),
      testCase(AssetTemplateTests.__allTests__AssetTemplateTests),
      testCase(ISDeviceIdiomProviderTests.__allTests__ISDeviceIdiomProviderTests),
      testCase(IdiomScaleProviderTests.__allTests__IdiomScaleProviderTests),
      testCase(ProductTests.__allTests__ProductTests),
      testCase(ValueAppearanceTests.__allTests__ValueAppearanceTests)
    ]
  }
#endif
