#if !canImport(ObjectiveC)
  import XCTest

  extension AssetSpecificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssetSpecificationTests = [
      ("testDecodingError", testDecodingError),
      ("testInvalidScale", testInvalidScale),
      ("testInvalidSize", testInvalidSize),
      ("testMetadata", testMetadata),
      ("testSpecifications", testSpecifications),
      ("testSuccessful", testSuccessful)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(AssetSpecificationTests.__allTests__AssetSpecificationTests)
    ]
  }
#endif
