name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare Build
      run: brew bundle
    - name: Build
      run: swift build -v
    - name: Lint
      run: swiftformat --lint . && swiftlint 
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Code Coverage 
      run: xcrun llvm-cov export -format="lcov" .build/debug/AssetLibPackageTests.xctest/Contents/MacOS/AssetLibPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Build Documentation
      run: sourcedocs generate --spm-module AssetLib --output-folder docs
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git diff-index --quiet HEAD || git commit -m "[github action] Update Docs"
    - name: Push changes
      run: git push HEAD:${GITHUB_REF}
      env:
        remote_repo: https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
