name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare Build
      run: brew bundle
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
