name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: GitHub Action for Homebrew
      uses: artemnovichkov/action-homebrew@0.1.0
      with:
        args: bundle install
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
